language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer config -g github-oauth.github.com $CI_USER_TOKEN

install:
  - composer install

script:
  - phpunit --coverage-text
