language: php

php:
  - 8.0
  - 8.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer config -g github-oauth.github.com $CI_USER_TOKEN
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --verbose
